### ISSUE TITLE
Swipe to vote?

### ISSUE THREAD

**Issue by masaom** [ahelfins/Democratic-DJ#13]
Change hard to press upvote and downvote buttons to a swipe to vote: swipe left to upvote, swipe right to downvote, change styling to be consistent with host song list page

**Comment by jinyoung-lim** [comment]
lets make more than one version of this to test! (EX: double-sided toggle?)

**Comment by masaom** [comment]
Idk how exactly to make different versions but we would just need to take out the swipeleft and swiperight in the HTML and uncomment the buttons to turn it back, so it's easy to switch back and forth
