### ISSUE TITLE
Multiple alerts (+ page refresh) when guests get kicked out (only sometimes)

### ISSUE THREAD

**Issue by jinyoung-lim** [ahelfins/Democratic-DJ#22]
As stated

**Comment by zskluzac** [comment]
I think we could take the alert out of guest-song-list, and instead just navigate to the host-guest page with a navparam that specifies whether the user was kicked out of the room and then display the alert in that case from host-guest. The subscribe function is calling alert multiple times.

**Comment by jinyoung-lim** [comment]
fixed and refactored
