### ISSUE TITLE
When multiple guests are using the app, it sometimes gets messed up when deleting, etc and freaks out? 

### ISSUE THREAD

**Issue by ahelfins** [ahelfins/Democratic-DJ#30]

**Comment by ahelfins** [comment]
It appears that this is giving reference child errors, so maybe it is still trying to display something in the list that was deleted?

**Comment by jinyoung-lim** [comment]
test a lot... to figure out when the issue occurs

**Comment by ahelfins** [comment]
We do not know exactly when this occurs, and it is not a fatal issue, so we will not fix it at the moment.
